version: '3'

services:

  # Dependencies

  redis:
    ports:
      - '${REDIS_PUBLIC_PORT}:6379'

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: 'local:redis:${REDIS_PORT}'
      HTTP_USER: '${REDIS_COMMANDER_USER}'
      HTTP_PASSWORD: '${REDIS_COMMANDER_PASSWORD}'
    ports:
      - '${REDIS_COMMANDER_PUBLIC_PORT}:8081'
    depends_on:
      redis:
        condition: service_healthy

  postgresql:
    ports:
      - '${POSTGRES_PUBLIC_HOST}:${POSTGRES_PUBLIC_PORT}:5432'

  rabbitmq:
    ports:
      - '${RABBITMQ_PUBLIC_PORT}:5672'
      - '${RABBITMQ_MANAGEMENT_PUBLIC_PORT}:15672'

  # Microservices
  
  gateway:
    stdin_open: true
    tty: true
    volumes:
      - ./apollo_gateway/:/app/
      - ./apollo_shared/:/shared/

  auth:
    stdin_open: true
    tty: true
    volumes:
      - ./apollo_auth/:/app/
      - ./apollo_shared/:/shared/

  rss:
    stdin_open: true
    tty: true
    volumes:
      - ./apollo_rss/:/app/
      - ./apollo_shared/:/shared/